### ISSUE TITLE
[FEAT] 공통 사용 컴포넌트

### ISSUE THREAD

**Issue by ReturnReason** [PuddyProject/Puddy_FrontEnd#1]
## 공통 컴포넌트 🐶
- [x] input
- [x] asterisk (*)
- [x] warning/correct message (필수 정보 입력, 비밀번호 일치 등)
- [x] button (fill, outline)
- [x] post button (연필 아이콘 버튼)
- [x] card (전문가, Q&A)
- [x] header nav bar
- [x] footer app bar (모바일 사이즈에서만 사용)
- [x] tag
- [x] modal
- [x] community card
- [x] loading
- 누락된 내용은 **코멘트** 부탁드립니다.

**Comment by vjvl95** [comment]
생각해보니 화면이 커지면 footer app bar 와 header nav bar 가 사라지고 위에 네비게이션 바가 생겨야 하는데 그 디자인이 빠진거 같습니다.


https://user-images.githubusercontent.com/62174495/226083735-152e9de6-4a77-47ee-ab85-9fa959e50f1e.mp4

**Comment by vjvl95** [comment]
저도 피그마 보면서 비교해봤는데 현재는 이정도 인 것 같습니다. 나중에 추가로 생각나면 알려드리겠습니다.
